name: wiih
description: A wine celler and wine notes app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  file_picker: ^8.0.7
  firebase_storage: ^13.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^1.0.6
  shared_preferences: ^2.0.10
  http: ^1.1.2
  flutter_image_compress: ^2.1.0
  numberpicker: ^2.0.0
  google_fonts: ^6.2.1 
  cloud_firestore: ^6.0.0
  firebase_app_check: ^0.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/app_logo.png
  adaptive_icon_background: "#FDEEEF"
  adaptive_icon_foreground: assets/app_icon_foreground.png
